### ISSUE TITLE
create healthReport query

### ISSUE THREAD

**Issue by matthewjwhitney** [MetaTech-dev/health-quiz-server#13]
- create a `query` that takes a parameter of `id` OR `personId` and a `resolver` that returns a single `HealthReport` that has an `id` or `peronsId` that matches that `id` or `personId` argument

**Comment by MetaMatt1** [comment]
I think we should actually split this into two queries, one would be healthReportById and has a required argument of id and one would be healthReportByPersonId and has a required argument of personId because the client could provide no arguments or both arguments which is not desirable.
