### ISSUE TITLE
feat(user): create user directory with typeDefs and resolvers

### ISSUE THREAD

**Issue by MetaMatt1** [MetaTech-dev/health-quiz-server#27]
- create new users directory with exported typeDefs and resolvers files
- import typeDefs and resolvers into schema and include users typeDefs and resolvers in corresponding merge
- create type with required id and email string and password string and personId ID
- create queries for get all users and get one user by id
- create mutations for create, update, and delete one user
`
const usersTestData = [
    {
        id: "aff1e95b-1b6d-44df-babf-d0548e59cf27",
        email: 'test@fake-email.com',
        password: "$2a$10$T3NwukZ8rNDuXTiu.pqbveyx7EMBcipN1A30BcbagfTJeC5KItTmS",
        personID: "23048073-d8e0-4b40-bb6a-72c5a1198f0e"
    },
    {
        id: "37bede16-aa7d-43a2-a8a8-429db71a6019",
        email: 'another.test@fake-email.com',
        password: "$2a$10$/wRL0WgmMXW4XmRV35cxjuKykOFGRH4Nhy5XgyQcmaHb7h6dNc7DO",
        personID: "79c5a40e-011f-4d47-ab8b-2cb066acefe8"
    },
]
`

**Comment by MetaMatt1** [comment]
get a branch with everything working except the hashing for the password, just accept a string right now and don't worry about hashing it. we'll add that funcitonality when we do the authentication workshop.

**Comment by metamang** [comment]
We should add a field resolver for person using the personId

**Comment by MetaMatt1** [comment]
> We should add a field resolver for person using the personId

Great idea @metamang! add it to your PR for this issue!
